### ISSUE TITLE
Open but don't switch window

### ISSUE THREAD

**Issue by KwatMDPhD** [tpapp/DefaultApplication.jl#16]
Is there a way to open with the default application, for example a web browser, and not switch to it? Perhaps wrapping the main call with some function that run the `Cmd` in the background?

**Comment by tpapp** [comment]
I think it is up to the application, I know of no general way to control this. If I remember correctly, Firefox has an option to disable it:

https://support.mozilla.org/en-US/questions/1297368

**Comment by tpapp** [comment]
Closing this as something outside the purposes of this package (for the moment).

In case someone knows of a generic way to do this, please comment here and I will reopen.
